package Riot.API.Riot.API.service;

import Riot.API.Riot.API.dto.datadragon.Item;
import Riot.API.Riot.API.dto.datadragon.Items;

import java.util.ArrayList;
import java.util.List;

public class ItemToItemList {

    static List<Item> ItemToItemList(Items result) {

        ArrayList<Item> list = new ArrayList<>();

        result.getData().getItem1001().setItemCode(1001);
        result.getData().getItem1004().setItemCode(1004);
        result.getData().getItem1006().setItemCode(1006);
        result.getData().getItem1011().setItemCode(1011);
        result.getData().getItem1018().setItemCode(1018);
        result.getData().getItem1026().setItemCode(1026);
        result.getData().getItem1027().setItemCode(1027);
        result.getData().getItem1028().setItemCode(1028);
        result.getData().getItem1029().setItemCode(1029);
        result.getData().getItem1031().setItemCode(1031);
        result.getData().getItem1033().setItemCode(1033);
        result.getData().getItem1035().setItemCode(1035);
        result.getData().getItem1036().setItemCode(1036);
        result.getData().getItem1037().setItemCode(1037);
        result.getData().getItem1038().setItemCode(1038);
        result.getData().getItem1039().setItemCode(1039);
        result.getData().getItem1040().setItemCode(1040);
        result.getData().getItem1042().setItemCode(1042);
        result.getData().getItem1043().setItemCode(1043);
        result.getData().getItem1052().setItemCode(1052);
        result.getData().getItem1053().setItemCode(1053);
        result.getData().getItem1054().setItemCode(1054);
        result.getData().getItem1055().setItemCode(1055);
        result.getData().getItem1056().setItemCode(1056);
        result.getData().getItem1057().setItemCode(1057);
        result.getData().getItem1058().setItemCode(1058);
        result.getData().getItem1082().setItemCode(1082);
        result.getData().getItem1083().setItemCode(1083);
        result.getData().getItem1500().setItemCode(1500);
        result.getData().getItem1501().setItemCode(1501);
        result.getData().getItem1502().setItemCode(1502);
        result.getData().getItem1503().setItemCode(1503);
        result.getData().getItem1504().setItemCode(1504);
        result.getData().getItem1505().setItemCode(1505);
        result.getData().getItem1506().setItemCode(1506);
        result.getData().getItem1507().setItemCode(1507);
        result.getData().getItem1508().setItemCode(1508);
        result.getData().getItem1509().setItemCode(1509);
        result.getData().getItem1510().setItemCode(1510);
        result.getData().getItem1511().setItemCode(1511);
        result.getData().getItem1512().setItemCode(1512);
        result.getData().getItem1515().setItemCode(1515);
        result.getData().getItem1516().setItemCode(1516);
        result.getData().getItem1517().setItemCode(1517);
        result.getData().getItem1518().setItemCode(1518);
        result.getData().getItem1519().setItemCode(1519);
        result.getData().getItem2003().setItemCode(2003);
        result.getData().getItem2010().setItemCode(2010);
        result.getData().getItem2015().setItemCode(2015);
        result.getData().getItem2031().setItemCode(2031);
        result.getData().getItem2033().setItemCode(2033);
        result.getData().getItem2051().setItemCode(2051);
        result.getData().getItem2052().setItemCode(2052);
        result.getData().getItem2055().setItemCode(2055);
        result.getData().getItem2065().setItemCode(2065);
        result.getData().getItem2138().setItemCode(2138);
        result.getData().getItem2139().setItemCode(2139);
        result.getData().getItem2140().setItemCode(2140);
        result.getData().getItem2403().setItemCode(2403);
        result.getData().getItem2419().setItemCode(2419);
        result.getData().getItem2420().setItemCode(2420);
        result.getData().getItem2421().setItemCode(2421);
        result.getData().getItem2422().setItemCode(2422);
        result.getData().getItem2423().setItemCode(2423);
        result.getData().getItem2424().setItemCode(2424);
        result.getData().getItem3001().setItemCode(3001);
        result.getData().getItem3003().setItemCode(3003);
        result.getData().getItem3004().setItemCode(3004);
        result.getData().getItem3006().setItemCode(3006);
        result.getData().getItem3009().setItemCode(3009);
        result.getData().getItem3011().setItemCode(3011);
        result.getData().getItem3020().setItemCode(3020);
        result.getData().getItem3024().setItemCode(3024);
        result.getData().getItem3026().setItemCode(3026);
        result.getData().getItem3031().setItemCode(3031);
        result.getData().getItem3033().setItemCode(3033);
        result.getData().getItem3035().setItemCode(3035);
        result.getData().getItem3036().setItemCode(3036);
        result.getData().getItem3040().setItemCode(3040);
        result.getData().getItem3041().setItemCode(3041);
        result.getData().getItem3042().setItemCode(3042);
        result.getData().getItem3044().setItemCode(3044);
        result.getData().getItem3046().setItemCode(3046);
        result.getData().getItem3047().setItemCode(3047);
        result.getData().getItem3050().setItemCode(3050);
        result.getData().getItem3051().setItemCode(3051);
        result.getData().getItem3053().setItemCode(3053);
        result.getData().getItem3057().setItemCode(3057);
        result.getData().getItem3065().setItemCode(3065);
        result.getData().getItem3066().setItemCode(3066);
        result.getData().getItem3067().setItemCode(3067);
        result.getData().getItem3068().setItemCode(3068);
        result.getData().getItem3070().setItemCode(3070);
        result.getData().getItem3071().setItemCode(3071);
        result.getData().getItem3072().setItemCode(3072);
        result.getData().getItem3074().setItemCode(3074);
        result.getData().getItem3075().setItemCode(3075);
        result.getData().getItem3076().setItemCode(3076);
        result.getData().getItem3077().setItemCode(3077);
        result.getData().getItem3078().setItemCode(3078);
        result.getData().getItem3082().setItemCode(3082);
        result.getData().getItem3083().setItemCode(3083);
        result.getData().getItem3085().setItemCode(3085);
        result.getData().getItem3086().setItemCode(3086);
        result.getData().getItem3089().setItemCode(3089);
        result.getData().getItem3091().setItemCode(3091);
        result.getData().getItem3094().setItemCode(3094);
        result.getData().getItem3095().setItemCode(3095);
        result.getData().getItem3100().setItemCode(3100);
        result.getData().getItem3102().setItemCode(3102);
        result.getData().getItem3105().setItemCode(3105);
        result.getData().getItem3107().setItemCode(3107);
        result.getData().getItem3108().setItemCode(3108);
        result.getData().getItem3109().setItemCode(3109);
        result.getData().getItem3110().setItemCode(3110);
        result.getData().getItem3111().setItemCode(3111);
        result.getData().getItem3112().setItemCode(3112);
        result.getData().getItem3113().setItemCode(3113);
        result.getData().getItem3114().setItemCode(3114);
        result.getData().getItem3115().setItemCode(3115);
        result.getData().getItem3116().setItemCode(3116);
        result.getData().getItem3117().setItemCode(3117);
        result.getData().getItem3119().setItemCode(3119);
        result.getData().getItem3121().setItemCode(3121);
        result.getData().getItem3123().setItemCode(3123);
        result.getData().getItem3124().setItemCode(3124);
        result.getData().getItem3133().setItemCode(3133);
        result.getData().getItem3134().setItemCode(3134);
        result.getData().getItem3135().setItemCode(3135);
        result.getData().getItem3139().setItemCode(3139);
        result.getData().getItem3140().setItemCode(3140);
        result.getData().getItem3142().setItemCode(3142);
        result.getData().getItem3143().setItemCode(3143);
        result.getData().getItem3145().setItemCode(3145);
        result.getData().getItem3152().setItemCode(3152);
        result.getData().getItem3153().setItemCode(3153);
        result.getData().getItem3155().setItemCode(3155);
        result.getData().getItem3156().setItemCode(3156);
        result.getData().getItem3157().setItemCode(3157);
        result.getData().getItem3158().setItemCode(3158);
        result.getData().getItem3165().setItemCode(3165);
        result.getData().getItem3177().setItemCode(3177);
        result.getData().getItem3179().setItemCode(3179);
        result.getData().getItem3181().setItemCode(3181);
        result.getData().getItem3184().setItemCode(3184);
        result.getData().getItem3190().setItemCode(3190);
        result.getData().getItem3191().setItemCode(3191);
        result.getData().getItem3193().setItemCode(3193);
        result.getData().getItem3211().setItemCode(3211);
        result.getData().getItem3222().setItemCode(3222);
        result.getData().getItem3330().setItemCode(3330);
        result.getData().getItem3340().setItemCode(3340);
        result.getData().getItem3363().setItemCode(3363);
        result.getData().getItem3364().setItemCode(3364);
        result.getData().getItem3400().setItemCode(3400);
        result.getData().getItem3504().setItemCode(3504);
        result.getData().getItem3508().setItemCode(3508);
        result.getData().getItem3513().setItemCode(3513);
        result.getData().getItem3599().setItemCode(3599);
        result.getData().getItem3600().setItemCode(3600);
        result.getData().getItem3742().setItemCode(3742);
        result.getData().getItem3748().setItemCode(3748);
        result.getData().getItem3801().setItemCode(3801);
        result.getData().getItem3802().setItemCode(3802);
        result.getData().getItem3814().setItemCode(3814);
        result.getData().getItem3850().setItemCode(3850);
        result.getData().getItem3851().setItemCode(3851);
        result.getData().getItem3853().setItemCode(3853);
        result.getData().getItem3854().setItemCode(3854);
        result.getData().getItem3855().setItemCode(3855);
        result.getData().getItem3857().setItemCode(3857);
        result.getData().getItem3858().setItemCode(3858);
        result.getData().getItem3859().setItemCode(3859);
        result.getData().getItem3860().setItemCode(3860);
        result.getData().getItem3862().setItemCode(3862);
        result.getData().getItem3863().setItemCode(3863);
        result.getData().getItem3864().setItemCode(3864);
        result.getData().getItem3901().setItemCode(3901);
        result.getData().getItem3902().setItemCode(3902);
        result.getData().getItem3903().setItemCode(3903);
        result.getData().getItem3916().setItemCode(3916);
        result.getData().getItem4005().setItemCode(4005);
        result.getData().getItem4401().setItemCode(4401);
        result.getData().getItem4403().setItemCode(4403);
        result.getData().getItem4628().setItemCode(4628);
        result.getData().getItem4629().setItemCode(4629);
        result.getData().getItem4630().setItemCode(4630);
        result.getData().getItem4632().setItemCode(4632);
        result.getData().getItem4633().setItemCode(4633);
        result.getData().getItem4635().setItemCode(4635);
        result.getData().getItem4636().setItemCode(4636);
        result.getData().getItem4637().setItemCode(4637);
        result.getData().getItem4638().setItemCode(4638);
        result.getData().getItem4641().setItemCode(4641);
        result.getData().getItem4642().setItemCode(4642);
        result.getData().getItem4643().setItemCode(4643);
        result.getData().getItem4644().setItemCode(4644);
        result.getData().getItem4645().setItemCode(4645);
        result.getData().getItem6029().setItemCode(6029);
        result.getData().getItem6035().setItemCode(6035);
        result.getData().getItem6333().setItemCode(6333);
        result.getData().getItem6609().setItemCode(6609);
        result.getData().getItem6616().setItemCode(6616);
        result.getData().getItem6617().setItemCode(6617);
        result.getData().getItem6630().setItemCode(6630);
        result.getData().getItem6631().setItemCode(6631);
        result.getData().getItem6632().setItemCode(6632);
        result.getData().getItem6653().setItemCode(6653);
        result.getData().getItem6655().setItemCode(6655);
        result.getData().getItem6656().setItemCode(6656);
        result.getData().getItem6660().setItemCode(6660);
        result.getData().getItem6662().setItemCode(6662);
        result.getData().getItem6664().setItemCode(6664);
        result.getData().getItem6670().setItemCode(6670);
        result.getData().getItem6671().setItemCode(6671);
        result.getData().getItem6672().setItemCode(6672);
        result.getData().getItem6673().setItemCode(6673);
        result.getData().getItem6675().setItemCode(6675);
        result.getData().getItem6676().setItemCode(6676);
        result.getData().getItem6677().setItemCode(6677);
        result.getData().getItem6691().setItemCode(6691);
        result.getData().getItem6692().setItemCode(6692);
        result.getData().getItem6693().setItemCode(6693);
        result.getData().getItem6694().setItemCode(6694);
        result.getData().getItem6695().setItemCode(6695);
        result.getData().getItem6696().setItemCode(6696);
        result.getData().getItem7000().setItemCode(7000);
        result.getData().getItem7001().setItemCode(7001);
        result.getData().getItem7002().setItemCode(7002);
        result.getData().getItem7003().setItemCode(7003);
        result.getData().getItem7004().setItemCode(7004);
        result.getData().getItem7005().setItemCode(7005);
        result.getData().getItem7006().setItemCode(7006);
        result.getData().getItem7007().setItemCode(7007);
        result.getData().getItem7008().setItemCode(7008);
        result.getData().getItem7009().setItemCode(7009);
        result.getData().getItem7010().setItemCode(7010);
        result.getData().getItem7011().setItemCode(7011);
        result.getData().getItem7012().setItemCode(7012);
        result.getData().getItem7013().setItemCode(7013);
        result.getData().getItem7014().setItemCode(7014);
        result.getData().getItem7015().setItemCode(7015);
        result.getData().getItem7016().setItemCode(7016);
        result.getData().getItem7017().setItemCode(7017);
        result.getData().getItem7018().setItemCode(7018);
        result.getData().getItem7019().setItemCode(7019);
        result.getData().getItem7020().setItemCode(7020);
        result.getData().getItem7021().setItemCode(7021);
        result.getData().getItem7022().setItemCode(7022);
        result.getData().getItem7023().setItemCode(7023);
        result.getData().getItem7024().setItemCode(7024);
        result.getData().getItem7050().setItemCode(7050);
        result.getData().getItem8001().setItemCode(8001);
        result.getData().getItem8020().setItemCode(8020);




        Item item = result.getData().getItem1001();
        list.add(item);
        item = result.getData().getItem1006();
        list.add(item);
        item = result.getData().getItem1011();
        list.add(item);
        item = result.getData().getItem1018();
        list.add(item);
        item = result.getData().getItem1026();
        list.add(item);
        item = result.getData().getItem1027();
        list.add(item);
        item = result.getData().getItem1028();
        list.add(item);
        item = result.getData().getItem1029();
        list.add(item);
        item = result.getData().getItem1031();
        list.add(item);
        item = result.getData().getItem1033();
        list.add(item);
        item = result.getData().getItem1035();
        list.add(item);
        item = result.getData().getItem1036();
        list.add(item);
        item = result.getData().getItem1037();
        list.add(item);
        item = result.getData().getItem1038();
        list.add(item);
        item = result.getData().getItem1039();
        list.add(item);
        item = result.getData().getItem1040();
        list.add(item);
        item = result.getData().getItem1042();
        list.add(item);
        item = result.getData().getItem1043();
        list.add(item);
        item = result.getData().getItem1052();
        list.add(item);
        item = result.getData().getItem1053();
        list.add(item);
        item = result.getData().getItem1054();
        list.add(item);
        item = result.getData().getItem1055();
        list.add(item);
        item = result.getData().getItem1056();
        list.add(item);
        item = result.getData().getItem1057();
        list.add(item);
        item = result.getData().getItem1058();
        list.add(item);
        item = result.getData().getItem1082();
        list.add(item);
        item = result.getData().getItem1083();
        list.add(item);
        item = result.getData().getItem1500();
        list.add(item);
        item = result.getData().getItem1501();
        list.add(item);
        item = result.getData().getItem1502();
        list.add(item);
        item = result.getData().getItem1503();
        list.add(item);
        item = result.getData().getItem1504();
        list.add(item);
        item = result.getData().getItem1505();
        list.add(item);
        item = result.getData().getItem1506();
        list.add(item);
        item = result.getData().getItem1507();
        list.add(item);
        item = result.getData().getItem1508();
        list.add(item);
        item = result.getData().getItem1509();
        list.add(item);
        item = result.getData().getItem1510();
        list.add(item);
        item = result.getData().getItem1511();
        list.add(item);
        item = result.getData().getItem1512();
        list.add(item);
        item = result.getData().getItem1515();
        list.add(item);
        item = result.getData().getItem1516();
        list.add(item);
        item = result.getData().getItem1517();
        list.add(item);
        item = result.getData().getItem1518();
        list.add(item);
        item = result.getData().getItem1519();
        list.add(item);
        item = result.getData().getItem2003();
        list.add(item);
        item = result.getData().getItem2010();
        list.add(item);
        item = result.getData().getItem2015();
        list.add(item);
        item = result.getData().getItem2031();
        list.add(item);
        item = result.getData().getItem2033();
        list.add(item);
        item = result.getData().getItem2051();
        list.add(item);
        item = result.getData().getItem2052();
        list.add(item);
        item = result.getData().getItem2055();
        list.add(item);
        item = result.getData().getItem2065();
        list.add(item);
        item = result.getData().getItem2138();
        list.add(item);
        item = result.getData().getItem2139();
        list.add(item);
        item = result.getData().getItem2140();
        list.add(item);
        item = result.getData().getItem2403();
        list.add(item);
        item = result.getData().getItem2419();
        list.add(item);
        item = result.getData().getItem2420();
        list.add(item);
        item = result.getData().getItem2421();
        list.add(item);
        item = result.getData().getItem2422();
        list.add(item);
        item = result.getData().getItem2423();
        list.add(item);
        item = result.getData().getItem2424();
        list.add(item);
        item = result.getData().getItem3001();
        list.add(item);
        item = result.getData().getItem3003();
        list.add(item);
        item = result.getData().getItem3004();
        list.add(item);
        item = result.getData().getItem3006();
        list.add(item);
        item = result.getData().getItem3009();
        list.add(item);
        item = result.getData().getItem3011();
        list.add(item);
        item = result.getData().getItem3020();
        list.add(item);
        item = result.getData().getItem3024();
        list.add(item);
        item = result.getData().getItem3026();
        list.add(item);
        item = result.getData().getItem3031();
        list.add(item);
        item = result.getData().getItem3033();
        list.add(item);
        item = result.getData().getItem3035();
        list.add(item);
        item = result.getData().getItem3036();
        list.add(item);
        item = result.getData().getItem3040();
        list.add(item);
        item = result.getData().getItem3041();
        list.add(item);
        item = result.getData().getItem3042();
        list.add(item);
        item = result.getData().getItem3044();
        list.add(item);
        item = result.getData().getItem3046();
        list.add(item);
        item = result.getData().getItem3047();
        list.add(item);
        item = result.getData().getItem3050();
        list.add(item);
        item = result.getData().getItem3051();
        list.add(item);
        item = result.getData().getItem3053();
        list.add(item);
        item = result.getData().getItem3057();
        list.add(item);
        item = result.getData().getItem3065();
        list.add(item);
        item = result.getData().getItem3066();
        list.add(item);
        item = result.getData().getItem3067();
        list.add(item);
        item = result.getData().getItem3068();
        list.add(item);
        item = result.getData().getItem3070();
        list.add(item);
        item = result.getData().getItem3071();
        list.add(item);
        item = result.getData().getItem3072();
        list.add(item);
        item = result.getData().getItem3074();
        list.add(item);
        item = result.getData().getItem3075();
        list.add(item);
        item = result.getData().getItem3076();
        list.add(item);
        item = result.getData().getItem3077();
        list.add(item);
        item = result.getData().getItem3078();
        list.add(item);
        item = result.getData().getItem3082();
        list.add(item);
        item = result.getData().getItem3083();
        list.add(item);
        item = result.getData().getItem3085();
        list.add(item);
        item = result.getData().getItem3086();
        list.add(item);
        item = result.getData().getItem3089();
        list.add(item);
        item = result.getData().getItem3091();
        list.add(item);
        item = result.getData().getItem3094();
        list.add(item);
        item = result.getData().getItem3095();
        list.add(item);
        item = result.getData().getItem3100();
        list.add(item);
        item = result.getData().getItem3102();
        list.add(item);
        item = result.getData().getItem3105();
        list.add(item);
        item = result.getData().getItem3107();
        list.add(item);
        item = result.getData().getItem3108();
        list.add(item);
        item = result.getData().getItem3109();
        list.add(item);
        item = result.getData().getItem3110();
        list.add(item);
        item = result.getData().getItem3111();
        list.add(item);
        item = result.getData().getItem3112();
        list.add(item);
        item = result.getData().getItem3113();
        list.add(item);
        item = result.getData().getItem3114();
        list.add(item);
        item = result.getData().getItem3115();
        list.add(item);
        item = result.getData().getItem3116();
        list.add(item);
        item = result.getData().getItem3117();
        list.add(item);
        item = result.getData().getItem3119();
        list.add(item);
        item = result.getData().getItem3121();
        list.add(item);
        item = result.getData().getItem3123();
        list.add(item);
        item = result.getData().getItem3124();
        list.add(item);
        item = result.getData().getItem3133();
        list.add(item);
        item = result.getData().getItem3134();
        list.add(item);
        item = result.getData().getItem3135();
        list.add(item);
        item = result.getData().getItem3139();
        list.add(item);
        item = result.getData().getItem3140();
        list.add(item);
        item = result.getData().getItem3142();
        list.add(item);
        item = result.getData().getItem3143();
        list.add(item);
        item = result.getData().getItem3145();
        list.add(item);
        item = result.getData().getItem3152();
        list.add(item);
        item = result.getData().getItem3153();
        list.add(item);
        item = result.getData().getItem3155();
        list.add(item);
        item = result.getData().getItem3156();
        list.add(item);
        item = result.getData().getItem3157();
        list.add(item);
        item = result.getData().getItem3158();
        list.add(item);
        item = result.getData().getItem3165();
        list.add(item);
        item = result.getData().getItem3177();
        list.add(item);
        item = result.getData().getItem3179();
        list.add(item);
        item = result.getData().getItem3181();
        list.add(item);
        item = result.getData().getItem3184();
        list.add(item);
        item = result.getData().getItem3190();
        list.add(item);
        item = result.getData().getItem3191();
        list.add(item);
        item = result.getData().getItem3193();
        list.add(item);
        item = result.getData().getItem3211();
        list.add(item);
        item = result.getData().getItem3222();
        list.add(item);
        item = result.getData().getItem3330();
        list.add(item);
        item = result.getData().getItem3340();
        list.add(item);
        item = result.getData().getItem3363();
        list.add(item);
        item = result.getData().getItem3364();
        list.add(item);
        item = result.getData().getItem3400();
        list.add(item);
        item = result.getData().getItem3504();
        list.add(item);
        item = result.getData().getItem3508();
        list.add(item);
        item = result.getData().getItem3513();
        list.add(item);
        item = result.getData().getItem3599();
        list.add(item);
        item = result.getData().getItem3600();
        list.add(item);
        item = result.getData().getItem3742();
        list.add(item);
        item = result.getData().getItem3748();
        list.add(item);
        item = result.getData().getItem3801();
        list.add(item);
        item = result.getData().getItem3802();
        list.add(item);
        item = result.getData().getItem3814();
        list.add(item);
        item = result.getData().getItem3850();
        list.add(item);
        item = result.getData().getItem3851();
        list.add(item);
        item = result.getData().getItem3853();
        list.add(item);
        item = result.getData().getItem3854();
        list.add(item);
        item = result.getData().getItem3855();
        list.add(item);
        item = result.getData().getItem3857();
        list.add(item);
        item = result.getData().getItem3858();
        list.add(item);
        item = result.getData().getItem3859();
        list.add(item);
        item = result.getData().getItem3860();
        list.add(item);
        item = result.getData().getItem3862();
        list.add(item);
        item = result.getData().getItem3863();
        list.add(item);
        item = result.getData().getItem3864();
        list.add(item);
        item = result.getData().getItem3901();
        list.add(item);
        item = result.getData().getItem3902();
        list.add(item);
        item = result.getData().getItem3903();
        list.add(item);
        item = result.getData().getItem3916();
        list.add(item);
        item = result.getData().getItem4005();
        list.add(item);
        item = result.getData().getItem4401();
        list.add(item);
        item = result.getData().getItem4403();
        list.add(item);
        item = result.getData().getItem4628();
        list.add(item);
        item = result.getData().getItem4629();
        list.add(item);
        item = result.getData().getItem4630();
        list.add(item);
        item = result.getData().getItem4632();
        list.add(item);
        item = result.getData().getItem4633();
        list.add(item);
        item = result.getData().getItem4635();
        list.add(item);
        item = result.getData().getItem4636();
        list.add(item);
        item = result.getData().getItem4637();
        list.add(item);
        item = result.getData().getItem4638();
        list.add(item);
        item = result.getData().getItem4641();
        list.add(item);
        item = result.getData().getItem4642();
        list.add(item);
        item = result.getData().getItem4643();
        list.add(item);
        item = result.getData().getItem4644();
        list.add(item);
        item = result.getData().getItem4645();
        list.add(item);
        item = result.getData().getItem6029();
        list.add(item);
        item = result.getData().getItem6035();
        list.add(item);
        item = result.getData().getItem6333();
        list.add(item);
        item = result.getData().getItem6609();
        list.add(item);
        item = result.getData().getItem6616();
        list.add(item);
        item = result.getData().getItem6617();
        list.add(item);
        item = result.getData().getItem6630();
        list.add(item);
        item = result.getData().getItem6631();
        list.add(item);
        item = result.getData().getItem6632();
        list.add(item);
        item = result.getData().getItem6653();
        list.add(item);
        item = result.getData().getItem6655();
        list.add(item);
        item = result.getData().getItem6656();
        list.add(item);
        item = result.getData().getItem6660();
        list.add(item);
        item = result.getData().getItem6662();
        list.add(item);
        item = result.getData().getItem6664();
        list.add(item);
        item = result.getData().getItem6670();
        list.add(item);
        item = result.getData().getItem6671();
        list.add(item);
        item = result.getData().getItem6672();
        list.add(item);
        item = result.getData().getItem6673();
        list.add(item);
        item = result.getData().getItem6675();
        list.add(item);
        item = result.getData().getItem6676();
        list.add(item);
        item = result.getData().getItem6677();
        list.add(item);
        item = result.getData().getItem6691();
        list.add(item);
        item = result.getData().getItem6692();
        list.add(item);
        item = result.getData().getItem6693();
        list.add(item);
        item = result.getData().getItem6694();
        list.add(item);
        item = result.getData().getItem6695();
        list.add(item);
        item = result.getData().getItem6696();
        list.add(item);
        item = result.getData().getItem7000();
        list.add(item);
        item = result.getData().getItem7001();
        list.add(item);
        item = result.getData().getItem7002();
        list.add(item);
        item = result.getData().getItem7003();
        list.add(item);
        item = result.getData().getItem7004();
        list.add(item);
        item = result.getData().getItem7005();
        list.add(item);
        item = result.getData().getItem7006();
        list.add(item);
        item = result.getData().getItem7007();
        list.add(item);
        item = result.getData().getItem7008();
        list.add(item);
        item = result.getData().getItem7009();
        list.add(item);
        item = result.getData().getItem7010();
        list.add(item);
        item = result.getData().getItem7011();
        list.add(item);
        item = result.getData().getItem7012();
        list.add(item);
        item = result.getData().getItem7013();
        list.add(item);
        item = result.getData().getItem7014();
        list.add(item);
        item = result.getData().getItem7015();
        list.add(item);
        item = result.getData().getItem7016();
        list.add(item);
        item = result.getData().getItem7017();
        list.add(item);
        item = result.getData().getItem7018();
        list.add(item);
        item = result.getData().getItem7019();
        list.add(item);
        item = result.getData().getItem7020();
        list.add(item);
        item = result.getData().getItem7021();
        list.add(item);
        item = result.getData().getItem7022();
        list.add(item);
        item = result.getData().getItem7023();
        list.add(item);
        item = result.getData().getItem7024();
        list.add(item);
        item = result.getData().getItem7050();
        list.add(item);
        item = result.getData().getItem8001();
        list.add(item);
        item = result.getData().getItem8020();
        list.add(item);
        return list;
    }
}
